# Generated by Django 2.2 on 2019-04-09 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Allergens',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the allergens, if any (e.g. Nuts)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the suisine (e.g. Mexican)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the food name (e.g. McDouble)', max_length=200)),
                ('allergens', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Allergens')),
            ],
        ),
        migrations.CreateModel(
            name='foodType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of food (e.g. Burger)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ingredientType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the type of ingredient (e.g. Onion)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a restaurant (e.g. Waffle House)', max_length=200)),
                ('summary', models.CharField(help_text='Enter a short description about the restaurant (e.g. Quick late-night breakfast joint)', max_length=200)),
                ('website', models.CharField(help_text='Enter a the official restaurant website (e.g. https://www.wafflehouse.com/)', max_length=200)),
                ('cuisine', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Cuisine')),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Food')),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the food name (e.g. McDouble)', max_length=200)),
                ('ingredientType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredientType')),
            ],
        ),
        migrations.AddField(
            model_name='food',
            name='foodType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.foodType'),
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Ingredients'),
        ),
    ]
