# Generated by Django 2.2 on 2019-04-09 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='menu',
            new_name='food',
        ),
    ]
