# Generated by Django 2.2 on 2019-04-09 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20190409_2119'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an allergen, if any (e.g. Nuts)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the ingredient name (e.g. Onion Powder)', max_length=200)),
                ('ingredientType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.ingredientType')),
            ],
        ),
        migrations.RemoveField(
            model_name='ingredients',
            name='ingredientType',
        ),
        migrations.AlterField(
            model_name='cuisine',
            name='name',
            field=models.CharField(help_text='Enter the cuisine (e.g. Mexican)', max_length=200),
        ),
        migrations.AlterField(
            model_name='food',
            name='allergens',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Allergen'),
        ),
        migrations.AlterField(
            model_name='food',
            name='ingredients',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.Ingredient'),
        ),
        migrations.DeleteModel(
            name='Allergens',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
    ]
