# Generated by Django 2.2 on 2019-04-09 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20190409_2124'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='food',
            new_name='menu',
        ),
    ]
