# Generated by Django 2.2 on 2019-04-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_auto_20190409_2127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='allergens',
        ),
        migrations.AddField(
            model_name='food',
            name='allergens',
            field=models.ManyToManyField(to='menu.Allergen'),
        ),
        migrations.RemoveField(
            model_name='food',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='food',
            name='ingredients',
            field=models.ManyToManyField(to='menu.Ingredient'),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisine',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisine',
            field=models.ManyToManyField(to='menu.Cuisine'),
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='menu',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='menu',
            field=models.ManyToManyField(to='menu.Food'),
        ),
    ]
